### ISSUE TITLE
API Key Authorization failure when using free API?

### ISSUE THREAD

**Issue by t0mcat1337** [juliushaertl/integration_deepl#4]
I just made a fresh account at deepl.com and registered the free version of the rest api for testing purposes.
I then copied the API Key and configured it as described (occ config:app:set integration_deepl apikey --value="xxxx").
But deepl integration isn't working, in Nextcloud Logs I find this error:

DeepL\AuthorizationException: Authorization failure, check authentication key

I double checked (and repeated) the configuration of the key and am sure it is 100% correct.

At deepl.com at the page where the api key is shown, I noticed this:

![grafik](https://user-images.githubusercontent.com/3826246/230997270-d744b8ee-d658-485e-b76e-a9a9357b831a.png)

So for the free API the URL to the API seems to be different than to the Pro (payed) API. I assume this could cause the above error?

**Comment by juliushaertl** [comment]
I've tested this also with the free api key. As we don't pass a URL according to the library we use it should pick up the default URL properly: 

https://github.com/DeepLcom/deepl-php#configuration

> server_url: string containing the URL of the DeepL API, can be overridden for example for testing purposes. By default, the URL is selected based on the user account type (free or paid).

**Comment by t0mcat1337** [comment]
@juliushaertl 
Thx for the reply... I also examined the code and (in Translator.php class) found out, that the URL is picked based on the auth key string... if the last 3 chars are ":fx" (which is in my case), then the free-api URL is used. 
Can't really figure out, what exactly was going wrong... the only thing I can say is, after a restart of the nextcloud container (my NC is running in Kubernetes) everything works now... strange...
